<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\AYIGroupMarket.Application\AYIGroupMarket.Application.csproj" />
    <ProjectReference Include="..\AYIGroupMarket.Infrastructure\AYIGroupMarket.Infrastructure.csproj" />
  </ItemGroup>


  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>AYIGroupMarket-Admin</UserSecretsId>
  </PropertyGroup>

</Project>
